#

name: cmake

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build kernel driver
      shell: bash
      run: make -C "${{runner.workspace}}"

    - name: cmake configure
      shell: bash
      run: cmake -S $GITHUB_WORKSPACE -B "${{runner.workspace}}/build"

    - name: cmake build
      shell: bash
      run: cmake --build "${{runner.workspace}}/build"
