#

name: cmake

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      shell: bash
      run: cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build

    - name: Build
      shell: bash
      run: cmake --build ${{runner.workspace}}/build
